name: Build & Test

on: [workflow_call, workflow_dispatch]

jobs:
  build:
    name: Build (${{ matrix.goos }}/${{ matrix.goarch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Set variables
        id: vars
        run: |
          # set the binary extension for Windows
          if [ "${{ matrix.goos }}" = "windows" ]; then
            echo "EXT=.exe" >> $GITHUB_OUTPUT
          else
            echo "EXT=" >> $GITHUB_OUTPUT
          fi
      - name: Build
        run: |
          mkdir dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -v -o dist/multisplit-${{ matrix.goos }}-${{ matrix.goarch }}${{ steps.vars.outputs.EXT }} ./cmd/multisplit
      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: multisplit-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Test multisplit
        run: go test -v ./...
  test-golangci-plugin:
    name: Test golangci-plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "golangci-plugin/go.mod"
          cache-dependency-path: "golangci-plugin/go.sum"
      - name: Test golangci-plugin
        working-directory: golangci-plugin
        run: go test -v ./...
