name: GHA
on: [push, pull_request, merge_group, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  codeql:
    name: CodeQL Analysis
    uses: ./.github/workflows/codeql.yml

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
      - codeql
      - test
    uses: ./.github/workflows/release.yml
