name: Release

on: [workflow_call, workflow_dispatch]

jobs:
  release:
    name: Stable
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download builds
        uses: actions/download-artifact@v8
        with:
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} ./dist/* \
            --title "MultiSplit ${{ github.ref_name }}" \
            --target ${{ github.sha }}
